# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - test
  - build

# Test the Spring Boot app
test-backend:
  stage: test
  image: eclipse-temurin:21-jdk
  before_script: apt-get update && apt-get install -y maven npm
  script:
    - mvn clean test
    - mvn build
  only:
    - branches  # Only run on branch pushes (e.g., feature branches)
  tags:
    - spring-boot

# Build the React app
build-frontend:
  stage: build
  image: node:16
  script:
    - cd reactapp  # Assuming your React app is in a folder called "frontend"
    - npm install
    - npm run build
  artifacts:
    paths:
      - reactapp/build  # Save the build output as an artifact
  only:
    - branches
  tags:
    - react

