version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: TicketManagerDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  springboot-app:
    build:
      context: "/home/dimitrios/Desktop/Eclipse/Eclipse Projects/Multi-module-project/springboot-app/"
    ports:
      - "8081:8081"       # Spring Boot app port
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/TicketManagerDB
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    volumes:
      - "/home/dimitrios/Desktop/Eclipse/Eclipse Projects/Multi-module-project/springboot-app/src/:/app/src"  # Source code for hot reloading
      - "/home/dimitrios/Desktop/Eclipse/Eclipse Projects/Multi-module-project/springboot-app/target:/app/target"  # Target directory for rebuilds
    networks:
      - app-network

  reactapp:
    build:
      context: "/home/dimitrios/Desktop/Eclipse/Eclipse Projects/Multi-module-project/reactapp/"
    ports:
      - "3000:3000"      # React app port
    depends_on:
      - springboot-app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "/home/dimitrios/Desktop/Eclipse/Eclipse Projects/Multi-module-project/reactapp/:/app"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
