version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: TicketManagerDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  springboot-app:
    build: /home/hacklberry/eclipse-workspace/Multi-module-project/springboot-app
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/TicketManagerDB
      DB_USERNAME: postgres
      DB_PASSWORD: 123
    networks:
      - app-network

  reactapp:
    build: /home/hacklberry/eclipse-workspace/Multi-module-project/reactapp
    ports:
      - "3000:80"
    depends_on:
      - springboot-app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
