name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/.ssh/github-ssh
          chmod 600 ~/.ssh/github-ssh
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config core.sshCommand "ssh -i ~/.ssh/github-ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

      - name: Push to GitLab
        run: |
          git remote add gitlab git@gitlab.com:Jimant2/ticket-manager.git
          git push --mirror gitlab
