name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$GITLAB_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          ssh -vT git@gitlab.com  # Verbose SSH output to test connectivity

      - name: Push to GitLab
        run: |
          git remote add gitlab git@gitlab.com:Jimant2/ticket-manager.git
          git push gitlab main
